vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+P1 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+P2 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+P3 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+P4 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+P5 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+P6 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+E1 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+E2 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+E3 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+E4 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+E5 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+E6 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+E7 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+E8 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+E9 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+E10 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+E11 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+E12 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+E13 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+E14 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+E15 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+E16 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+E17 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+E18 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+E19 +define+POST +define+SDF
vcs -f rtl.f -full64 -R -debug_access+all +v2k +maxdelays -negdelay +neg_tchk +define+E20 +define+POST +define+SDF
