vcs -full64 -R +define+P1  -f run_all_filelist.f | tee P1.log
vcs -full64 -R +define+P2  -f run_all_filelist.f | tee P2.log
vcs -full64 -R +define+P3  -f run_all_filelist.f | tee P3.log
vcs -full64 -R +define+P4  -f run_all_filelist.f | tee P4.log
vcs -full64 -R +define+P5  -f run_all_filelist.f | tee P5.log
vcs -full64 -R +define+P6  -f run_all_filelist.f | tee P6.log
vcs -full64 -R +define+E1  -f run_all_filelist.f | tee E1.log
vcs -full64 -R +define+E2  -f run_all_filelist.f | tee E2.log
vcs -full64 -R +define+E3  -f run_all_filelist.f | tee E3.log
vcs -full64 -R +define+E4  -f run_all_filelist.f | tee E4.log
vcs -full64 -R +define+E5  -f run_all_filelist.f | tee E5.log
vcs -full64 -R +define+E6  -f run_all_filelist.f | tee E6.log
vcs -full64 -R +define+E7  -f run_all_filelist.f | tee E7.log
vcs -full64 -R +define+E8  -f run_all_filelist.f | tee E8.log
vcs -full64 -R +define+E9  -f run_all_filelist.f | tee E9.log
vcs -full64 -R +define+E10 -f run_all_filelist.f | tee E10.log
vcs -full64 -R +define+E11 -f run_all_filelist.f | tee E11.log
vcs -full64 -R +define+E12 -f run_all_filelist.f | tee E12.log
vcs -full64 -R +define+E13 -f run_all_filelist.f | tee E13.log
vcs -full64 -R +define+E14 -f run_all_filelist.f | tee E14.log
vcs -full64 -R +define+E15 -f run_all_filelist.f | tee E15.log
vcs -full64 -R +define+E16 -f run_all_filelist.f | tee E16.log
vcs -full64 -R +define+E17 -f run_all_filelist.f | tee E17.log
vcs -full64 -R +define+E18 -f run_all_filelist.f | tee E18.log
vcs -full64 -R +define+E19 -f run_all_filelist.f | tee E19.log
vcs -full64 -R +define+E20 -f run_all_filelist.f | tee E20.log
